### ISSUE TITLE
Download script erroring on Snort Static after Downloading MD5

### ISSUE THREAD

**Issue by crazydude86** [SkiTheSlicer/securityonion-airgap#1]
Below is where the download script ran and where the error occurred:

python securityonion_airgap_download.py -e  ****.****@*********.com (sanitized email)
Output Dir: so-airgap-20170124-1049

[GeoIP]
Downloading GeoIP.dat.gz...
Decompressing GeoIP.dat.gz...
Downloading GeoIPv6.dat.gz...
Decompressing GeoIPv6.dat.gz...
Downloading GeoLiteCity.dat.gz...
Decompressing GeoLiteCity.dat.gz...
Downloading GeoLiteCityv6.dat.gz...
Decompressing GeoLiteCityv6.dat.gz...

[RIR]
Downloading delegated-afrinic-extended-latest...
Downloading delegated-afrinic-extended-latest.md5...
Downloading delegated-apnic-extended-latest...
Downloading delegated-apnic-extended-latest.md5...
Downloading delegated-arin-extended-latest...
Downloading delegated-arin-extended-latest.md5...
Downloading delegated-lacnic-extended-latest...
Downloading delegated-lacnic-extended-latest.md5...
Downloading delegated-ripencc-extended-latest...
Downloading delegated-ripencc-extended-latest.md5...
Checking MD5 for delegated-arin-extended-latest...
  MD5 OK
Checking MD5 for delegated-lacnic-extended-latest...
  MD5 OK
Checking MD5 for delegated-ripencc-extended-latest...
  MD5 OK
Checking MD5 for delegated-apnic-extended-latest...
  MD5 OK
Checking MD5 for delegated-afrinic-extended-latest...
  MD5 OK

[Snort Static]
Downloading community-rules.tar.gz...
Downloading md5s...
Traceback (most recent call last):
  File "securityonion_airgap_download.py", line 267, in <module>
    main()
  File "securityonion_airgap_download.py", line 234, in main
    requests_download_file(url[1], os.path.join(args.output_dir, "Snort", url[0]))
  File "securityonion_airgap_download.py", line 109, in requests_download_file
    r = requests.get(url_to_download, stream=True)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='labs.snort.org', port=80): Max retries exceeded with url: /feeds/ip-filter.blf (Caused by <class 'socket.gaierror'>: [Errno -5] No address associated with hostname)

**Comment by SkiTheSlicer** [comment]
Looks like the URL changed. Updated. Thanks for the report.
